import assert from 'node:assert/strict';
import { calculateStats, defaultSelection, randomSelection } from '../../dist/assets/game/data/planeParts.js';
import { normalizeSave } from '../../dist/assets/game/systems/SaveSystem.js';
import { buildResult, judgeRating } from '../../dist/assets/game/systems/ResultSystem.js';
const stats=calculateStats(defaultSelection); assert.deepEqual(stats,{speed:3,lift:4,control:5,energy:3});
for(const body of ['round','speed','large']) for(const wing of ['wide','swift','float']) for(const engine of ['gentle','power','eco']){const s=calculateStats({body,wing,engine,color:'blue'}); Object.values(s).forEach(v=>assert.ok(v>=1&&v<=5));}
assert.equal(randomSelection(()=>0).body,'round'); assert.equal(randomSelection(()=>0.99).engine,'eco');
assert.equal(normalizeSave('bad').selection.body,'round'); assert.equal(normalizeSave({version:0,selection:{body:'speed',wing:'swift',engine:'eco',color:'red'},bestDistance:5}).version,4);
assert.equal(judgeRating({body:'large',wing:'float',engine:'eco',color:'green'},1000,3,0),'エコフライト名人');
const save=normalizeSave({bestDistance:10,bestStars:1,bestGoldStars:0}); const r=buildResult(defaultSelection,20.7,2,1,3,save); assert.equal(r.isBestDistance,true); assert.equal(r.distance,20);
console.log('logic tests passed');
import { defaultResearchSettings, simulateFlight, compareWithReal } from '../../dist/assets/game/systems/ResearchPhysics.js';
const base={...defaultResearchSettings};
const narrow=simulateFlight({...base,wingWidth:1}); const wide=simulateFlight({...base,wingWidth:5}); assert.ok(wide.timeRange[1]>narrow.timeRange[1]);
const front=simulateFlight({...base,centerOfGravity:'front'}); const back=simulateFlight({...base,centerOfGravity:'backish'}); assert.ok(front.stability>back.stability); assert.ok(back.stall>front.stall);
assert.equal(simulateFlight({...base,balance:'leftUp'}).mainType,'左へ旋回'); assert.equal(simulateFlight({...base,balance:'rightUp'}).mainType,'右へ旋回');
assert.ok(simulateFlight({...base,throwPower:'strong'}).distanceRange[1]>simulateFlight({...base,throwPower:'gentle'}).distanceRange[1]);
const sameA=simulateFlight(base), sameB=simulateFlight(base); assert.deepEqual(sameA.distanceRange,sameB.distanceRange);
for (const r of [simulateFlight({...base,wingWidth:5,throwPower:'strong'}), simulateFlight({...base,wingWidth:1,throwPower:'gentle',centerOfGravity:'backish'})]) { assert.ok(r.distanceRange[0]>=2&&r.distanceRange[1]<=21); assert.ok(r.timeRange[0]>=0.8&&r.timeRange[1]<=8.3); }
const cmp=compareWithReal(sameA,{distance:1,time:1,traits:['急に落ちた','左へ曲がった'],throwPower:'normal',memo:''}); assert.ok(cmp.suggestions.some(s=>s.includes('つばさ'))); assert.ok(cmp.different.includes('急に落ちた'));
const migrated=normalizeSave({version:1,bestDistance:3}); assert.deepEqual(migrated.researchRecords,[]); assert.equal(migrated.researchBestDistance,0);
console.log('research tests passed');
import { rankForPoints, updateMissions, discoverCards, makeSavedPlane, autoPlaneName, diffResults, settingsKey, canAward, pointsFor } from '../../dist/assets/game/systems/ResearchProgression.js';
assert.equal(rankForPoints(0),'かけだし研究員'); assert.equal(rankForPoints(100),'紙ひこうき研究員'); assert.equal(rankForPoints(900),'かわかわマスター');
const cardSettings={...base,basePlane:'glider',wingWidth:5,throwPower:'gentle'}; const simWide=simulateFlight(cardSettings); const gotCards=discoverCards(cardSettings,simWide,[]); assert.ok(gotCards.some(c=>c.id==='float-combo'||c.id==='wide-slow'));
let mission=updateMissions(normalizeSave({}).missions,{settings:{...base,balance:'leftUp'},result:simulateFlight({...base,balance:'leftUp'}),triedTypes:['speed','glider','balance'],cardCount:5}); assert.ok(mission.completed.some(m=>m.id==='turn-left')); assert.ok(mission.completed.some(m=>m.id==='three-types')); assert.ok(mission.completed.some(m=>m.id==='cards5'));
assert.equal(canAward('firstSim',[]),true); assert.equal(canAward('firstSim',['firstSim']),false); assert.equal(pointsFor('firstSim'),10); assert.equal(settingsKey(base),settingsKey({...base}));
const plane=makeSavedPlane({id:'p1',name:autoPlaneName(0),settings:base,result:sameA,now:'2026-07-15T00:00:00.000Z'}); assert.equal(plane.name,'そらかぜ1号'); assert.equal(plane.simulationHistory.length,1);
const save20=normalizeSave({savedPlanes:Array.from({length:25},(_,i)=>({...plane,id:'p'+i,name:'n'+i}))}); assert.equal(save20.savedPlanes.length,20);
const renamed={...plane,name:'新しい名前'}; assert.equal(renamed.name,'新しい名前');
const d=diffResults(sameA,simulateFlight({...base,wingWidth:5})); assert.ok(typeof d.distance==='number'); assert.ok(d.tradeoff.length>0);
const migrated2=normalizeSave({version:1,bestDistance:7,researchRecords:[{id:'old',settings:base,simulation:sameA,createdAt:'x',bestDistance:4}]}); assert.equal(migrated2.version,4); assert.equal(migrated2.bestDistance,7); assert.equal(migrated2.researchRecords.length,1); assert.equal(migrated2.researchPoints,0);
assert.deepEqual(simulateFlight({...base,wingWidth:2,throwPower:'strong'}),simulateFlight({...base,wingWidth:2,throwPower:'strong'}));
console.log('progression tests passed');
import { addMaterial, calculatePlaneStats, canCraft, craftPart, createDigGrid, emptyMaterials, improvementSuggestions, missionCatalog2, partCatalog, rewardForCell, testFlight, updateBuildMissions } from '../../dist/assets/game/systems/BuildGame.js';
const grid=createDigGrid(4); assert.equal(grid.length,16); assert.equal(grid.find(c=>c.type==='soft')?.maxHp,2); assert.equal(grid.find(c=>c.type==='normal')?.maxHp,3); assert.equal(grid.find(c=>c.type==='hard')?.maxHp,4);
assert.ok(grid.map(c=>rewardForCell(c,4)).filter(Boolean).length>=5);
let inv=emptyMaterials(); inv=addMaterial(inv,'wood',2); inv=addMaterial(inv,'screw',1); assert.equal(inv.wood,2); assert.equal(canCraft(inv,partCatalog.lightBody).ok,true); let crafted=craftPart(inv,{},'lightBody'); assert.equal(crafted.ok,true); assert.equal(crafted.inventory.wood,0); assert.equal(crafted.crafted.lightBody,1);
assert.equal(canCraft(emptyMaterials(),partCatalog.powerEngine).ok,false); assert.ok(canCraft(emptyMaterials(),partCatalog.powerEngine).missing.length>0);
const buildPlane={body:'lightBody',wing:'wideWing',tail:'steadyTail',engine:'smallEngine',propeller:'woodProp',tire:'smallTire'}; const ps=calculatePlaneStats(buildPlane); assert.ok(ps.speed>1&&ps.straight>1&&ps.endurance>1); const fr=testFlight(buildPlane); assert.ok(fr.distance>=10); assert.ok(!/失敗|ゲームオーバー/.test(fr.note+fr.good+fr.advice));
const sug=improvementSuggestions({}); assert.equal(sug.length,3); assert.equal(sug[0].title,'つばさを広くする');
const buildSave=normalizeSave({version:1,materials:{wood:4},currentPlane:buildPlane,craftedParts:{wideWing:1}}); assert.equal(buildSave.version,4); assert.equal(buildSave.materials.wood,4); assert.deepEqual(buildSave.researchRecords,[]);
const progressed=updateBuildMissions(buildSave,{type:'flight',value:12}); assert.ok(progressed.some(m=>m.id==='wood3'&&m.completed)); assert.ok(progressed.some(m=>m.id==='firstPlane'&&m.completed)); assert.ok(progressed.some(m=>m.id==='fly10'&&m.completed)); assert.equal(missionCatalog2.length>=5,true);
console.log('build-game tests passed');

import { answerQuestion, blueprintCatalog, calculateQuizReward, generateQuizQuestion, mergeQuizReward, startQuizSession } from '../../dist/assets/game/systems/QuizSystem.js';
const eq1=generateQuizQuestion('easy',123,0), eq2=generateQuizQuestion('easy',123,0); assert.deepEqual(eq1,eq2); assert.ok(['かず','かたち','ひらがな','いろ','なかまわけ'].includes(eq1.category));
const cq=generateQuizQuestion('challenge',123,1); assert.ok(['たしざん','ひきざん','かんじ','とけい','ずけい','ぶんしょう'].includes(cq.category));
for(let i=0;i<20;i++){const q=generateQuizQuestion('easy',200+i,i); if(q.category==='かず') assert.ok(Number(q.choices[q.answerIndex])>=1&&Number(q.choices[q.answerIndex])<=10); assert.ok(q.choices.length>=2&&q.choices.length<=3);}
const sess=startQuizSession('easy',55); assert.equal(sess.questionIds.length,5); const q0=generateQuizQuestion('easy',55,0); const ans=answerQuestion(sess,q0.answerIndex); assert.equal(ans.correctCount,1); assert.equal(ans.streak,1);
let wrong=answerQuestion(sess,(q0.answerIndex+1)%q0.choices.length); assert.equal(wrong.correctCount,0); const minReward=calculateQuizReward(0,0); assert.ok(Object.values(minReward.materials).some(n=>n>0));
const streakReward=calculateQuizReward(3,3); assert.ok(streakReward.fragments>=1); assert.ok(streakReward.materials.screw>=1);
const fullReward=calculateQuizReward(5,5); assert.ok(fullReward.fragments>=1); let quizSave=normalizeSave({version:3,materials:{wood:4},savedBuildPlanes:[{id:'b',name:'n',parts:{},stats:{speed:1,straight:1,tough:1,endurance:1},flightCount:0,bestDistance:0,bestTime:0,createdAt:'x',updatedAt:'x'}]}); assert.equal(quizSave.version,4); assert.equal(quizSave.materials.wood,4); assert.equal(quizSave.savedBuildPlanes.length,1);
const merged=mergeQuizReward(quizSave,{...fullReward,fragments:5}); assert.ok(merged.unlockedBlueprints.includes('wideWing')); assert.ok(merged.unlockedBlueprints.includes('powerEngine')); assert.ok(blueprintCatalog.length>=2);
const mid=answerQuestion(startQuizSession('challenge',77),0); const resumed=normalizeSave({currentQuizSession:mid}); assert.equal(resumed.currentQuizSession.currentIndex,1); assert.equal(resumed.currentQuizSession.completed,false);
console.log('quiz tests passed');
