import { defaultSelection } from '../data/planeParts.js'; import type { FlightResult, PlaneSelection, SaveData } from '../types/game.js';
import { missionCatalog, rankForPoints } from './ResearchProgression.js';
import { createDigGrid, emptyMaterials, missionCatalog2 } from './BuildGame.js';
export const SAVE_KEY='kawakawa-flight-save'; const VERSION=3;
const fallback:SaveData={version:VERSION,selection:defaultSelection,bestDistance:0,bestStars:0,bestGoldStars:0,soundOn:true,hasSeenHowTo:false,researchRecords:[],researchBestDistance:0,researchPoints:0,researchRank:'かけだし研究員',missions:missionCatalog,discoveredCards:[],savedPlanes:[],improvementHistory:[],awardedActionKeys:[],triedBasePlanes:[],materials:emptyMaterials(),discoveredMaterials:[],craftedParts:{},currentPlane:{},savedBuildPlanes:[],digProgress:createDigGrid(3),buildMissions:missionCatalog2,tutorialProgress:[],tutorialCompleted:false,inventorySeen:false,lastScreen:'title'}; let memory={...fallback};
function isSelection(v:unknown):v is PlaneSelection{const s=v as PlaneSelection; return !!s&&['round','speed','large'].includes(s.body)&&['wide','swift','float'].includes(s.wing)&&['gentle','power','eco'].includes(s.engine)&&['red','blue','yellow','green','purple','orange'].includes(s.color)}
const arr=<T>(v:unknown,max=100):T[]=>Array.isArray(v)?(v as T[]).slice(0,max):[];
export function normalizeSave(raw:unknown):SaveData{if(!raw||typeof raw!=='object')return{...fallback}; const r=raw as Partial<SaveData>; const points=typeof r.researchPoints==='number'?Math.max(0,r.researchPoints):0; const missions=missionCatalog.map(m=>({...m,...arr<SaveData['missions'][number]>(r.missions).find(x=>x.id===m.id)})); return{version:VERSION,selection:isSelection(r.selection)?r.selection:defaultSelection,bestDistance:typeof r.bestDistance==='number'?Math.max(0,r.bestDistance):0,bestStars:typeof r.bestStars==='number'?Math.max(0,r.bestStars):0,bestGoldStars:typeof r.bestGoldStars==='number'?Math.max(0,r.bestGoldStars):0,soundOn:typeof r.soundOn==='boolean'?r.soundOn:true,hasSeenHowTo:typeof r.hasSeenHowTo==='boolean'?r.hasSeenHowTo:false,researchRecords:arr(r.researchRecords,50),researchBestDistance:typeof r.researchBestDistance==='number'?Math.max(0,r.researchBestDistance):0,researchPoints:points,researchRank:rankForPoints(points),missions,discoveredCards:arr(r.discoveredCards,50),savedPlanes:arr(r.savedPlanes,20),activePlaneId:typeof r.activePlaneId==='string'?r.activePlaneId:undefined,improvementHistory:arr(r.improvementHistory,80),lastResearchSession:r.lastResearchSession,awardedActionKeys:arr<string>(r.awardedActionKeys,300),triedBasePlanes:arr<string>(r.triedBasePlanes,3),materials:{...emptyMaterials(),...(r.materials||{})},discoveredMaterials:arr(r.discoveredMaterials,20),craftedParts:r.craftedParts&&typeof r.craftedParts==='object'?r.craftedParts:{},currentPlane:r.currentPlane&&typeof r.currentPlane==='object'?r.currentPlane:{},savedBuildPlanes:arr(r.savedBuildPlanes,20),digProgress:arr(r.digProgress,16).length?arr(r.digProgress,16):createDigGrid(3),buildMissions:missionCatalog2.map(m=>({...m,...arr<SaveData['buildMissions'][number]>(r.buildMissions).find(x=>x.id===m.id)})),tutorialProgress:arr(r.tutorialProgress,20),tutorialCompleted:!!r.tutorialCompleted,inventorySeen:!!r.inventorySeen,lastScreen:typeof r.lastScreen==='string'?r.lastScreen:'title',activeBuildPlaneId:typeof r.activeBuildPlaneId==='string'?r.activeBuildPlaneId:undefined};}
function cloneSave(data:SaveData):SaveData{return typeof structuredClone==='function'?structuredClone(data):JSON.parse(JSON.stringify(data)) as SaveData;}
export class SaveSystem{static load():SaveData{try{const text=globalThis.localStorage?.getItem(SAVE_KEY); memory=text?normalizeSave(JSON.parse(text)):memory;}catch{memory=normalizeSave(memory)} return cloneSave(memory);} static save(patch:Partial<SaveData>):SaveData{const next={...memory,...patch,version:VERSION}; next.researchRank=rankForPoints(next.researchPoints??0); memory=normalizeSave(next); try{globalThis.localStorage?.setItem(SAVE_KEY,JSON.stringify(memory));}catch{/* memory fallback */} return cloneSave(memory);} static updateBest(result:Pick<FlightResult,'distance'|'stars'|'goldStars'>):SaveData{const s=this.load(); return this.save({bestDistance:Math.max(s.bestDistance,Math.floor(result.distance)),bestStars:Math.max(s.bestStars,result.stars),bestGoldStars:Math.max(s.bestGoldStars,result.goldStars)});} static addResearchRecord(record:SaveData['researchRecords'][number]):SaveData{const s=this.load(); const records=[record,...s.researchRecords].slice(0,50); return this.save({researchRecords:records,researchBestDistance:Math.max(s.researchBestDistance,record.bestDistance)});}}
