import './ui/styles.css';
import { AudioSystem } from './game/systems/AudioSystem.js';
import { SaveSystem } from './game/systems/SaveSystem.js';
import { addMaterial, calculatePlaneStats, canCraft, categories, categoryNames, craftPart, createDigGrid, improvementSuggestions, materialIds, materials, partCatalog, rewardForCell, testFlight, updateBuildMissions } from './game/systems/BuildGame.js';
import type { BuildPartId, CurrentPlane, MaterialId, SavedBuildPlane, SaveData } from './game/types/game.js';

type Screen='title'|'dig'|'bag'|'craft'|'assemble'|'test'|'myPlanes'|'records'|'settings'|'research';
const foundApp=document.getElementById('game-container'); if(!foundApp) throw new Error('game-container element was not found'); const app=foundApp;
let screen:Screen='title'; let save=SaveSystem.load(); let lastFlight:ReturnType<typeof testFlight>|null=null; let digSeed=Date.now()%999; let hammer=-1;
const partIds=Object.keys(partCatalog) as BuildPartId[]; const jp={speed:'はやさ',straight:'まっすぐ',tough:'つよさ',endurance:'ながくとべる'} as const;
function btn(label:string, fn:()=>void, cls='primary'){const b=document.createElement('button'); b.className=`game-btn ${cls}`; b.textContent=label; b.onclick=()=>{void AudioSystem.resume(); AudioSystem.play('button'); fn();}; return b;}
function icon(id:string){return `<svg class="ico ${id}" viewBox="0 0 64 64" aria-hidden="true"><use href="#i-${id}"></use></svg>`}
function defs(){return `<svg width="0" height="0" class="defs"><defs><symbol id="i-wood" viewBox="0 0 64 64"><rect x="10" y="22" width="44" height="24" rx="9" fill="#b8793b"/><path d="M18 30h28M22 38h22" stroke="#70451f" stroke-width="4"/></symbol><symbol id="i-metal" viewBox="0 0 64 64"><path d="M14 20h36l-8 28H8z" fill="#9fb7c9" stroke="#557" stroke-width="4"/></symbol><symbol id="i-screw" viewBox="0 0 64 64"><circle cx="32" cy="32" r="18" fill="#c8d6e5" stroke="#557" stroke-width="4"/><path d="M22 32h20" stroke="#557" stroke-width="5"/></symbol><symbol id="i-cloth" viewBox="0 0 64 64"><path d="M14 14h36v36H14z" fill="#ffcfdf"/><path d="M14 28h36M28 14v36" stroke="#c75" stroke-width="3"/></symbol><symbol id="i-propeller" viewBox="0 0 64 64"><circle cx="32" cy="32" r="6" fill="#445"/><ellipse cx="32" cy="15" rx="7" ry="15" fill="#74b9ff"/><ellipse cx="32" cy="49" rx="7" ry="15" fill="#74b9ff"/><ellipse cx="15" cy="32" rx="15" ry="7" fill="#74b9ff"/><ellipse cx="49" cy="32" rx="15" ry="7" fill="#74b9ff"/></symbol><symbol id="i-engine" viewBox="0 0 64 64"><rect x="14" y="20" width="36" height="26" rx="8" fill="#576574"/><circle cx="46" cy="33" r="9" fill="#ff9f43"/></symbol><symbol id="i-lightMetal" viewBox="0 0 64 64"><path d="M32 6l8 18 18 8-18 8-8 18-8-18-18-8 18-8z" fill="#dff9ff" stroke="#00a8ff" stroke-width="4"/></symbol><symbol id="i-strongWing" viewBox="0 0 64 64"><path d="M8 40C24 14 44 10 58 20 44 30 30 40 8 40z" fill="#a3e4a6" stroke="#278a45" stroke-width="4"/></symbol></defs></svg>`}
function savePatch(p:Partial<SaveData>){save=SaveSystem.save(p)}
function missionsHtml(limit=3){const active=save.buildMissions.filter(m=>!m.completed).slice(0,limit); return `<div class="mission-box ${limit===1?'compact':''}"><h3>いまのミッション</h3>${active.map(m=>`<p><span>${m.title}</span><br><progress max="${m.goal}" value="${m.progress}"></progress> <b>${Math.floor(m.progress)}/${m.goal}</b></p>`).join('')||'<p>ぜんぶできたよ。すきな飛行機を作ろう！</p>'}</div>`}
function kaz(msg:string){return `<div class="guide"><div class="doctor">カゼ博士</div><p>${msg}</p></div>`}
function render(){save=SaveSystem.load(); app.innerHTML=defs(); app.className=`screen ${screen}`; ({title,dig,bag,craft,assemble,test,myPlanes,records,settings,research} as Record<Screen,()=>void>)[screen](); savePatch({lastScreen:screen});}
function title(){const s=document.createElement('section'); s.className='panel title-panel'; s.innerHTML=`<div class="cloud c1"></div><div class="cloud c2"></div><h1>かわかわふらいと</h1><div class="hero-svg home-hero">${planeSvg(save.currentPlane)}</div>${kaz('材料をほって、飛行機を作ろう！')}`; const digBtn=btn('ほってあつめる',()=>{if(!save.digProgress.some(c=>!c.revealed))savePatch({digProgress:createDigGrid(++digSeed)});screen='dig';render();},'primary home-primary'); const missionWrap=document.createElement('div'); missionWrap.className='home-mission'; missionWrap.innerHTML=missionsHtml(1); const missionButton=btn('ミッションを見る',()=>{screen='records';render();},'secondary'); missionWrap.append(missionButton); const grid=document.createElement('div'); grid.className='home-grid'; grid.append(btn('ひこうきをつくる',()=>{screen='craft';render();},'mode-card'),btn('テストフライト',()=>{screen='test';render();},'mode-card'),btn('マイひこうき',()=>{screen='myPlanes';render();},'mode-card'));
const sub=document.createElement('div'); sub.className='button-row'; sub.append(btn('ざいりょうバッグ',()=>{screen='bag';render();},'secondary'),btn('きろく',()=>{screen='records';render();},'secondary'),btn('せってい',()=>{screen='settings';render();},'secondary'),btn('紙ひこうき研究',()=>{screen='research';render();},'secondary')); s.append(digBtn,missionWrap,grid,sub); app.append(s);}
function dig(){const p=document.createElement('section'); p.className='panel dig-panel'; p.innerHTML=`<header class="topbar"><button class="game-btn secondary" id="back">ホーム</button><h2>ほってあつめる</h2><button class="game-btn secondary" id="new">新しい土</button></header>${kaz('マスをタップしてハンマーでトントン。キラキラはレア素材のチャンスじゃ。')}`; p.querySelector('#back')!.addEventListener('click',()=>{screen='title';render()}); p.querySelector('#new')!.addEventListener('click',()=>{savePatch({digProgress:createDigGrid(++digSeed)});render()}); const grid=document.createElement('div'); grid.className='dig-grid'; save.digProgress.forEach(cell=>{const b=btn('',()=>hit(cell.id),'dirt '+cell.type+(cell.sparkle?' sparkle':'')+(cell.revealed?' revealed':'')+(hammer===cell.id?' hammer':'') ); b.innerHTML=cell.revealed?(cell.reward?icon(cell.reward):'<span class="empty">からっぽ</span>'):`<span class="cracks">${'✕'.repeat(cell.maxHp-cell.hp)}</span><small>${cell.type==='soft'?'やわらかい':cell.type==='normal'?'ふつう':'かたい'}</small>`; grid.append(b);}); p.append(grid); const got=materialIds.filter(id=>save.materials[id]>0).map(id=>`${materials[id].name}:${save.materials[id]}`).join('　'); p.append(Object.assign(document.createElement('p'),{textContent:got||'まだ材料はないよ'}),btn('バッグを見る',()=>{screen='bag';render();},'secondary')); app.append(p);}
function hit(id:number){let grid=save.digProgress.map(c=>({...c})); const c=grid[id]; if(c.revealed)return; hammer=id; c.hp--; if(c.hp<=0){c.revealed=true; c.reward=rewardForCell(c,digSeed); if(c.reward){const mats=addMaterial(save.materials,c.reward); const disc=[...new Set([...save.discoveredMaterials,c.reward])]; savePatch({materials:mats,discoveredMaterials:disc,digProgress:grid}); savePatch({buildMissions:updateBuildMissions(SaveSystem.load(),{type:'dig'})}); AudioSystem.play('discover');} else savePatch({digProgress:grid});} else {savePatch({digProgress:grid}); AudioSystem.play('part');} setTimeout(()=>{hammer=-1;render()},140); render();}
function bag(){const p=document.createElement('section'); p.className='panel'; p.innerHTML=`<header class="topbar"><button class="game-btn secondary" id="back">ホーム</button><h2>ざいりょうバッグ</h2><span></span></header>${kaz('0この材料も、見つけるまではシルエットでひみつじゃ。')}`; p.querySelector('#back')!.addEventListener('click',()=>{screen='title';render()}); const grid=document.createElement('div'); grid.className='inventory-grid'; materialIds.forEach(id=>{const found=save.discoveredMaterials.includes(id)||save.materials[id]>0; const d=document.createElement('div'); d.className='item-card '+(found?'':'locked'); d.innerHTML=`${found?icon(id):'<div class="silhouette"></div>'}<h3>${found?materials[id].name:'？？？'}</h3><b>${save.materials[id]}こ</b><p>${found?materials[id].description:'土の中にかくれているよ'}</p><small>${found?materials[id].uses:'見つけてからのおたのしみ'}</small>`; grid.append(d);}); p.append(grid,btn('部品を作る',()=>{screen='craft';render();})); app.append(p);}
function craft(){const p=document.createElement('section'); p.className='panel'; p.innerHTML=`<header class="topbar"><button class="game-btn secondary" id="back">ホーム</button><h2>ひこうきをつくる</h2><button class="game-btn secondary" id="bag">バッグ</button></header>${kaz('作れる部品は明るく見えるぞ。足りない材料は赤く出るのじゃ。')}`; p.querySelector('#back')!.addEventListener('click',()=>{screen='title';render()}); p.querySelector('#bag')!.addEventListener('click',()=>{screen='bag';render()}); categories.forEach(cat=>{const sec=document.createElement('div'); sec.className='craft-section'; sec.innerHTML=`<h3>${categoryNames[cat]}</h3>`; partIds.filter(id=>partCatalog[id].category===cat).forEach(id=>{const part=partCatalog[id], check=canCraft(save.materials,part); const c=document.createElement('div'); c.className='craft-card '+(check.ok?'can':'cant'); c.innerHTML=`<h3>${part.name}</h3><p>${part.description}</p><div class="recipe">${Object.entries(part.recipe).map(([m,n])=>`<span class="${(save.materials[m as MaterialId]??0)<(n??0)?'missing':''}">${materials[m as MaterialId].name} ${save.materials[m as MaterialId]??0}/${n}</span>`).join('')}</div><p>${Object.entries(part.stats).map(([k,v])=>`${jp[k as keyof typeof jp]} +${v}`).join(' / ')}</p>`; c.append(btn(save.craftedParts[id]?'もう1こ作る':'作る',()=>{const r=craftPart(save.materials,save.craftedParts as Record<BuildPartId,number>,id); if(!r.ok){alert('材料がたりないよ。ほって集めよう！');return} savePatch({materials:r.inventory,craftedParts:r.crafted}); let ns=SaveSystem.load(); savePatch({buildMissions:updateBuildMissions(ns,{type:'craft'})}); AudioSystem.play('discover'); render();},check.ok?'primary':'secondary')); sec.append(c);}); p.append(sec);}); p.append(btn('組み立てへ',()=>{screen='assemble';render();})); app.append(p);}
function assemble(){const p=document.createElement('section'); p.className='panel'; const stats=calculatePlaneStats(save.currentPlane); p.innerHTML=`<header class="topbar"><button class="game-btn secondary" id="back">ホーム</button><h2>組み立て</h2><button class="game-btn secondary" id="save">保存</button></header><div class="hero-svg big">${planeSvg(save.currentPlane)}</div><div class="stats">${Object.entries(stats).map(([k,v])=>`<p>${jp[k as keyof typeof jp]} <span>${'●'.repeat(Math.min(10,v))}</span></p>`).join('')}</div>`; p.querySelector('#back')!.addEventListener('click',()=>{screen='title';render()}); p.querySelector('#save')!.addEventListener('click',savePlane); categories.forEach(cat=>{const row=document.createElement('div'); row.className='slot-row'; row.innerHTML=`<h3>${categoryNames[cat]}</h3>`; partIds.filter(id=>partCatalog[id].category===cat&&(save.craftedParts[id]??0)>0).forEach(id=>row.append(btn(partCatalog[id].name,()=>{const before=save.currentPlane.engine; const plane={...save.currentPlane,[cat]:id}; savePatch({currentPlane:plane}); let s=SaveSystem.load(); savePatch({buildMissions:updateBuildMissions(s,{type:before&&cat==='engine'&&before!==id?'engineSwap':'assemble'})}); render();},save.currentPlane[cat]===id?'chip selected':'chip'))); if(row.children.length===1)row.append(Object.assign(document.createElement('p'),{textContent:'まだ部品がないよ'})); p.append(row);}); p.append(btn('テストフライト',()=>{screen='test';render();})); app.append(p);}
function test(){lastFlight=testFlight(save.currentPlane, save.savedBuildPlanes.find(p=>p.id===save.activeBuildPlaneId)?.flightCount??0); const complete=categories.every(c=>save.currentPlane[c]); const p=document.createElement('section'); p.className='panel result-panel'; p.innerHTML=`<header class="topbar"><button class="game-btn secondary" id="back">ホーム</button><h2>テストフライト</h2><span></span></header><div class="flight-scene">${planeSvg(save.currentPlane)}</div><h3>${complete?'ナイスフライト！':'まだ部品をつけるともっと飛ぶよ'}</h3><p>飛んだ距離 ${lastFlight.distance}m / 飛んだ時間 ${lastFlight.time}秒</p><p>${lastFlight.note}</p><p>${lastFlight.good}</p><p>${lastFlight.advice}</p><h3>つぎの改良候補</h3>`; p.querySelector('#back')!.addEventListener('click',()=>{screen='title';render()}); improvementSuggestions(save.currentPlane).forEach(s=>p.append(Object.assign(document.createElement('div'),{className:'suggestion',innerHTML:`<b>${s.title}</b><p>${s.before} → ${s.after}</p>`}))); p.append(btn('1か所かえる',()=>{screen='assemble';render();}),btn('材料をほる',()=>{screen='dig';render();},'secondary'),btn('マイひこうきに保存',savePlane,'secondary')); savePatch({buildMissions:updateBuildMissions(SaveSystem.load(),{type:'flight',value:lastFlight.distance})}); app.append(p);}
function savePlane(){const now=new Date().toISOString(), stats=calculatePlaneStats(save.currentPlane); const names=['そらいちごう','つばさにごう','はやぶささんごう']; const id=save.activeBuildPlaneId||'build-'+Date.now(); const old=save.savedBuildPlanes.find(p=>p.id===id); const f=lastFlight; const plane:SavedBuildPlane={id,name:old?.name||names[save.savedBuildPlanes.length%names.length],parts:{...save.currentPlane},stats,flightCount:(old?.flightCount??0)+(f?1:0),bestDistance:Math.max(old?.bestDistance??0,f?.distance??0),bestTime:Math.max(old?.bestTime??0,f?.time??0),lastFlownAt:f?now:old?.lastFlownAt,createdAt:old?.createdAt||now,updatedAt:now}; savePatch({savedBuildPlanes:[plane,...save.savedBuildPlanes.filter(p=>p.id!==id)].slice(0,20),activeBuildPlaneId:id}); alert('マイひこうきに保存したよ'); render();}
function myPlanes(){const p=document.createElement('section'); p.className='panel'; p.innerHTML=`<header class="topbar"><button class="game-btn secondary" id="back">ホーム</button><h2>マイひこうき</h2><span></span></header>`; p.querySelector('#back')!.addEventListener('click',()=>{screen='title';render()}); save.savedBuildPlanes.forEach(x=>{const c=document.createElement('div'); c.className='note-card'; c.innerHTML=`<h3>${x.name}</h3><p>飛行回数 ${x.flightCount} / ベスト ${x.bestDistance}m・${x.bestTime}秒</p><p>最後 ${x.lastFlownAt?new Date(x.lastFlownAt).toLocaleString('ja-JP'):'これから'}</p>${planeSvg(x.parts)}`; c.append(btn('のせかえる',()=>{savePatch({currentPlane:x.parts,activeBuildPlaneId:x.id});screen='assemble';render();},'secondary')); p.append(c);}); if(!save.savedBuildPlanes.length)p.append(Object.assign(document.createElement('p'),{textContent:'まだ保存した飛行機がないよ'})); app.append(p);}
function records(){const p=document.createElement('section'); p.className='panel'; p.innerHTML=`<button class="game-btn secondary" id="back">ホーム</button><h2>ずかん・きろく</h2>${missionsHtml()}<h3>見つけた材料</h3><p>${save.discoveredMaterials.map(id=>materials[id].name).join('、')||'これから'}</p><h3>作った部品</h3><p>${Object.entries(save.craftedParts).filter(([,n])=>(n??0)>0).map(([id,n])=>`${partCatalog[id as BuildPartId].name} ${n}`).join('、')||'これから'}</p>`; p.querySelector('#back')!.addEventListener('click',()=>{screen='title';render()}); app.append(p);}
function settings(){const p=document.createElement('section'); p.className='panel'; p.innerHTML='<button class="game-btn secondary" id="back">ホーム</button><h2>せってい</h2>'; p.querySelector('#back')!.addEventListener('click',()=>{screen='title';render()}); p.append(btn(save.soundOn?'音 オン':'音 オフ',()=>{savePatch({soundOn:AudioSystem.toggle()});render();}),btn('発掘をやりなおす',()=>{savePatch({digProgress:createDigGrid(++digSeed)});screen='dig';render();},'secondary')); app.append(p);}
function research(){const p=document.createElement('section'); p.className='panel'; p.innerHTML='<h2>紙ひこうき研究（サブモード）</h2><p>新しいメインゲームは「材料をほる→飛行機を作る」です。研究記録の保存データは残しています。</p>'; p.append(btn('ホーム',()=>{screen='title';render();},'secondary')); app.append(p);}
function planeSvg(plane:CurrentPlane){const body=plane.body?'#ffcf5a':'#d9e6ef', wing=plane.wing?'#74b9ff':'#c8d6e5', tail=plane.tail?'#55efc4':'#c8d6e5', engine=plane.engine?'#576574':'#a4b0be', prop=plane.propeller?'#ffeaa7':'#dfe6e9', tire=plane.tire?'#2f3542':'#a4b0be'; return `<svg class="plane-art" viewBox="0 0 320 160"><path d="M72 82 C105 42 208 38 262 72 C230 112 116 120 72 82Z" fill="${body}" stroke="#18415a" stroke-width="6"/><path d="M132 78 L62 136 L202 104 Z" fill="${wing}" stroke="#18415a" stroke-width="6"/><path d="M91 69 L46 35 L112 50 Z" fill="${tail}" stroke="#18415a" stroke-width="6"/><circle cx="262" cy="75" r="18" fill="${engine}" stroke="#18415a" stroke-width="6"/><path d="M262 38v74M225 75h74" stroke="${prop}" stroke-width="10" stroke-linecap="round"/><circle cx="132" cy="119" r="12" fill="${tire}"/><circle cx="215" cy="107" r="12" fill="${tire}"/><rect x="174" y="58" width="34" height="20" rx="8" fill="#fff" opacity=".8"/></svg>`}
try{render();}catch(e){console.error(e); const er=document.getElementById('startup-error'); if(er)er.style.display='block';}
