import './ui/styles.css';
import { bodies, calculateStats, colors, defaultSelection, engines, getPart, nextId, randomSelection, statStars, wings } from './game/data/planeParts.js';
import { SaveSystem } from './game/systems/SaveSystem.js';
import { AudioSystem } from './game/systems/AudioSystem.js';
import { buildResult } from './game/systems/ResultSystem.js';
import type { FlightResult, PlaneSelection, Stats } from './game/types/game.js';

type Screen='title'|'workshop'|'flight'|'result';
const gameContainer=document.getElementById('game-container');
if(!gameContainer) throw new Error('game-container element was not found');
const app=gameContainer;
let save=SaveSystem.load(); let selection={...save.selection}; let result:FlightResult|null=null; let screen:Screen='title';
function btn(label:string, onClick:()=>void, cls='primary'){const b=document.createElement('button'); b.className=`game-btn ${cls}`; b.textContent=label; b.ariaLabel=label; b.onclick=()=>{void AudioSystem.resume(); AudioSystem.play('button'); onClick();}; return b;}
function render(){app.innerHTML=''; app.className=`screen ${screen}`; if(screen==='title')title(); if(screen==='workshop')workshop(); if(screen==='flight')flight(); if(screen==='result')resultScreen();}
function title(){const box=document.createElement('section'); box.className='panel title-panel'; box.innerHTML='<div class="cloud c1"></div><div class="cloud c2"></div><h1>かわかわふらいと</h1><p>そらの工房で ひこうきをつくって とばそう！</p><div class="hero-plane">✈️</div>'; const row=document.createElement('div'); row.className='button-row'; row.append(btn('はじめる',()=>{screen='workshop';render();}),btn('あそびかた',()=>{save=SaveSystem.save({hasSeenHowTo:true}); alert('① ひこうきをつくろう\n② がめんをおすと上にとぶよ\n③ ほしをあつめよう');})); box.append(row, btn(save.soundOn?'音 オン':'音 オフ',()=>{save=SaveSystem.save({soundOn:AudioSystem.toggle()});render();},'secondary')); app.append(box);}
function partRow<T extends string>(title:string, parts:{id:T;name:string;description:string}[], current:T, set:(id:T)=>void){const wrap=document.createElement('div'); wrap.className='part-row'; const label=document.createElement('h3'); label.textContent=title; const cards=document.createElement('div'); cards.className='cards'; const left=btn('←',()=>set(nextId(parts as never,current as never,-1) as T),'round'); const right=btn('→',()=>set(nextId(parts as never,current as never,1) as T),'round'); parts.forEach(p=>{const c=btn(`${p.name}\n${p.description}`,()=>set(p.id),p.id===current?'card selected':'card'); cards.append(c);}); wrap.append(label,left,cards,right); return wrap;}
function workshop(){const stats=calculateStats(selection); const panel=document.createElement('section'); panel.className='workshop-panel'; const head=document.createElement('header'); head.className='topbar'; head.append(btn('ホーム',()=>{screen='title';render();},'secondary'),Object.assign(document.createElement('h2'),{textContent:'ひこうき工房'}),btn(save.soundOn?'音オン':'音オフ',()=>{save=SaveSystem.save({soundOn:AudioSystem.toggle()});render();},'secondary')); const preview=document.createElement('canvas'); preview.width=720; preview.height=260; preview.className='plane-preview'; drawPlane(preview.getContext('2d')!,360,135,1.45,selection,0); const stat=document.createElement('div'); stat.className='stats'; stat.innerHTML=Object.entries({speed:'はやさ',lift:'うきやすさ',control:'そうじゅう',energy:'エネルギー'}).map(([k,n])=>`<p>${n} <span>${statStars(stats[k as keyof Stats])}</span></p>`).join(''); const set=(s:Partial<PlaneSelection>)=>{selection={...selection,...s}; save=SaveSystem.save({selection}); AudioSystem.play('part'); render();}; const colorsBox=document.createElement('div'); colorsBox.className='color-row'; colors.forEach(c=>{const b=btn(c.id===selection.color?'✓ '+c.name:c.name,()=>set({color:c.id}),'swatch'); b.style.background=c.css; b.style.color=c.id==='yellow'?'#18415a':'white'; if(c.id===selection.color)b.classList.add('selected'); colorsBox.append(b);}); const actions=document.createElement('div'); actions.className='button-row'; actions.append(btn('テストフライト',()=>{AudioSystem.play('start');screen='flight';render();}),btn('ランダムでつくる',()=>set(randomSelection()),'secondary'),btn('さいしょにもどす',()=>set(defaultSelection),'secondary')); panel.append(head,preview,stat,partRow('胴体',bodies,selection.body,id=>set({body:id})),partRow('翼',wings,selection.wing,id=>set({wing:id})),partRow('エンジン',engines,selection.engine,id=>set({engine:id})),colorsBox,actions); app.append(panel);}
function flight(){const canvas=document.createElement('canvas'); canvas.className='flight-canvas'; app.append(canvas); const ui=document.createElement('div'); ui.className='flight-ui'; const pause=btn('一時停止',()=>paused=!paused,'secondary'); const quit=btn('工房へ',()=>{paused=true;if(confirm('フライトをやめて工房にもどる？')){screen='workshop';render();}else paused=false;},'secondary'); ui.append(pause,quit,btn(save.soundOn?'音オン':'音オフ',()=>{save=SaveSystem.save({soundOn:AudioSystem.toggle()});},'secondary')); app.append(ui); const ctx=canvas.getContext('2d')!; const stats=calculateStats(selection); let w=0,h=0,y=0,vy=0,t=0,dist=0,stars=0,gold=0,energy=100,paused=false,press=false; const starList:{x:number;y:number;gold:boolean;got:boolean}[]=[]; const resize=()=>{w=canvas.width=innerWidth*devicePixelRatio; h=canvas.height=innerHeight*devicePixelRatio; canvas.style.width='100%'; canvas.style.height='100%'; if(!y)y=h*.45}; resize(); addEventListener('resize',resize); const down=(e:Event)=>{e.preventDefault();press=true}; const up=()=>press=false; canvas.addEventListener('pointerdown',down); addEventListener('pointerup',up); addEventListener('keydown',e=>{if(e.code==='Space')press=true;if(e.code==='KeyP')paused=!paused}); addEventListener('keyup',e=>{if(e.code==='Space')press=false}); for(let i=0;i<44;i++)starList.push({x:w*.75+i*150*devicePixelRatio,y:h*(.32+.18*Math.sin(i*.7)),gold:i%17===8,got:false}); let last=performance.now(); const loop=(now:number)=>{if(screen!=='flight'){removeEventListener('resize',resize);return} const dt=Math.min(.033,(now-last)/1000); last=now; if(!paused){t+=dt; const speed=(170+stats.speed*28)*devicePixelRatio; dist+=speed*dt/8; energy-=dt*(2.0+(6-stats.energy)*.45); const grav=(42+(6-stats.lift)*18)*devicePixelRatio; const thrust=(92+stats.control*18)*devicePixelRatio; vy+=(press&&energy>0?-thrust:grav)*dt; vy*=.985; y+=vy*dt; y=Math.max(h*.12,Math.min(h*.78,y)); if(y>=h*.78&&energy<8)energy=0; starList.forEach(s=>{s.x-=speed*dt; if(!s.got&&Math.hypot(s.x-w*.22,s.y-y)<(s.gold?44:32)*devicePixelRatio){s.got=true; s.gold?gold++:stars++; AudioSystem.play(s.gold?'gold':'star');}}); if(energy<=0||t>45){const old=SaveSystem.load(); result=buildResult(selection,dist,stars,gold,t,old); SaveSystem.updateBest(result); AudioSystem.play('result'); screen='result'; render(); return;}} drawFlight(ctx,w,h,y,vy,selection,dist,stars,gold,energy,starList,t); requestAnimationFrame(loop)}; requestAnimationFrame(loop);}
function resultScreen(){const r=result; if(!r){screen='title';render();return} const panel=document.createElement('section'); panel.className='panel result-panel'; panel.innerHTML=`<h2>ナイスフライト！</h2><canvas id="result-plane" width="560" height="190"></canvas><p class="rating">${r.rating}</p><p>きょり ${r.distance} m ${r.isBestDistance?'🎉 自己ベスト！':''}</p><p>ほし ${r.stars} 　金のほし ${r.goldStars}</p><p>ベスト: ${SaveSystem.load().bestDistance} m / ほし ${SaveSystem.load().bestStars} / 金 ${SaveSystem.load().bestGoldStars}</p>`; const row=document.createElement('div'); row.className='button-row'; row.append(btn('もういちど とぶ',()=>{screen='flight';render();}),btn('工房にもどる',()=>{screen='workshop';render();},'secondary'),btn('はじめにもどる',()=>{screen='title';render();},'secondary')); panel.append(row); app.append(panel); drawPlane((document.getElementById('result-plane') as HTMLCanvasElement).getContext('2d')!,280,95,1.15,r.selection,0);}
function drawPlane(ctx:CanvasRenderingContext2D,x:number,y:number,s:number,sel:PlaneSelection,rot:number){const color=colors.find(c=>c.id===sel.color)!.css; const body=getPart(bodies,sel.body), wing=getPart(wings,sel.wing), engine=getPart(engines,sel.engine); ctx.save(); ctx.translate(x,y); ctx.rotate(rot); ctx.scale(s,s); ctx.fillStyle=color; ctx.strokeStyle='#18415a'; ctx.lineWidth=4; const bl=[115,145,130][body.shape], bh=[38,30,50][body.shape]; ctx.beginPath(); ctx.ellipse(0,0,bl/2,bh/2,0,0,Math.PI*2); ctx.fill(); ctx.stroke(); ctx.fillStyle='rgba(255,255,255,.75)'; ctx.fillRect(10,-12,28,18); ctx.fillStyle=color; ctx.beginPath(); const ww=[100,82,118][wing.shape], wy=[46,28,54][wing.shape]; ctx.moveTo(-20,0); ctx.lineTo(-65,wy); ctx.lineTo(ww*.35,18); ctx.closePath(); ctx.fill(); ctx.stroke(); ctx.beginPath(); ctx.moveTo(-45,-6); ctx.lineTo(-78,-38); ctx.lineTo(-28,-20); ctx.closePath(); ctx.fill(); ctx.stroke(); ctx.fillStyle='#555'; const er=[13,18,11][engine.shape]; ctx.beginPath(); ctx.arc(bl/2+8,0,er,0,Math.PI*2); ctx.fill(); ctx.stroke(); ctx.strokeStyle='#fff7ad'; ctx.beginPath(); ctx.moveTo(bl/2+8,-28); ctx.lineTo(bl/2+8,28); ctx.moveTo(bl/2-18,0); ctx.lineTo(bl/2+34,0); ctx.stroke(); ctx.restore();}
function drawFlight(ctx:CanvasRenderingContext2D,w:number,h:number,y:number,vy:number,sel:PlaneSelection,dist:number,stars:number,gold:number,energy:number,starList:{x:number;y:number;gold:boolean;got:boolean}[],t:number){ctx.clearRect(0,0,w,h); const g=ctx.createLinearGradient(0,0,0,h); g.addColorStop(0,'#8fe3ff'); g.addColorStop(1,'#dff9ff'); ctx.fillStyle=g; ctx.fillRect(0,0,w,h); ctx.fillStyle='#75d686'; ctx.fillRect(0,h*.82,w,h*.18); ctx.fillStyle='#ffffffaa'; for(let i=0;i<8;i++){const x=(i*240-(t*80)%(240))*devicePixelRatio; ctx.beginPath(); ctx.ellipse(x,h*(.15+(i%3)*.12),70,25,0,0,Math.PI*2);ctx.fill()} starList.forEach(s=>{if(s.got)return; ctx.fillStyle=s.gold?'#ffd33d':'#fff28a'; ctx.font=`${s.gold?42:30}px sans-serif`; ctx.fillText('★',s.x,s.y)}); drawPlane(ctx,w*.22,y,devicePixelRatio*.85,sel,Math.max(-.28,Math.min(.28,vy/600))); ctx.fillStyle='#18415a'; ctx.font=`${22*devicePixelRatio}px sans-serif`; ctx.fillText(`きょり ${Math.floor(dist)}m  ほし ${stars}  金 ${gold}`,20*devicePixelRatio,34*devicePixelRatio); ctx.fillStyle='#fff'; ctx.fillRect(20*devicePixelRatio,50*devicePixelRatio,180*devicePixelRatio,20*devicePixelRatio); ctx.fillStyle=energy<25?'#ff9f43':'#67d66f'; ctx.fillRect(20*devicePixelRatio,50*devicePixelRatio,Math.max(0,energy)*1.8*devicePixelRatio,20*devicePixelRatio); ctx.strokeStyle='#18415a';ctx.strokeRect(20*devicePixelRatio,50*devicePixelRatio,180*devicePixelRatio,20*devicePixelRatio); if(innerHeight>innerWidth){ctx.fillStyle='rgba(255,255,255,.85)'; ctx.fillRect(w*.16,h*.35,w*.68,h*.16); ctx.fillStyle='#18415a'; ctx.fillText('横むきだと あそびやすいよ',w*.22,h*.44)} }
try{render();}catch(error){console.error('Startup failed',error); const e=document.getElementById('startup-error'); if(e)e.style.display='block';}
